### ISSUE TITLE
Failed to activate the d-struct package

### ISSUE THREAD

**Issue by aquaratixc** [ysgard/d-struct#8]
1. Open any dub projects
2. d-structs -> dub build

**Atom Version**: 1.0.2
**System**: Ubuntu 15.04
**Thrown From**: [d-struct](https://github.com/ysgard/d-struct) package, v1.0.4
### Stack Trace

Failed to activate the d-struct package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/home/thinker/.atom/packages/d-struct/lib/d-struct.coffee:18:32)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
    at /usr/share/atom/resources/app.asar/src/package.js:772:25
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:222:20)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
```
### Commands

```
     -0:02.3.0 d-struct:dub-build (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-dlang, v1.1.2
d-struct, v1.0.4
language-d, v3.2.1
linter-dscanner, v0.1.0
minimap, v4.10.2
tested, v0.5.0

# Dev
No dev packages
```

**Comment by aaronhyperum** [comment]
With the same configuration on a Mac OSX 10.11, Macbook Air 13-inch 2013, I have the exact same problem as well.

**Comment by earthfront** [comment]
Same problem, different packages.

**Comment by pirocks** [comment]
Same problem windows 8.1

**Comment by laberba** [comment]
Problem still persists in ubuntu linux

**Comment by osmarks** [comment]
Same problem on Arch Linux, but the problem occurs on activation of the package.

**Comment by MggMuggins** [comment]
Persisting on Ubuntu 16.04 LTS, also occurs upon activation of the package.

**Comment by MggMuggins** [comment]
Right, I understand why this is happening. This package uses a depreciated API, which is completely gone from newer versions of atom. I've forked the repository and am attempting to update the package. I don't know CoffeeScript, so this will be a fun time.

**Comment by aberba** [comment]
Ok, please post update here

**Comment by MggMuggins** [comment]
Alright, I've updated the depreciated features, but I'm also going to include linux support in my commit.

**Comment by MggMuggins** [comment]
I've opened #9 to fix depreciated features. Is someone willing to test for me on Windows or Mac and see if either dub command does anything? I'm interested to see what happens for you guys, so that I can potentially fix more things.

**Comment by ysgard** [comment]
Closing as this was fixed, but not published.  I've published a new version of the package.
